### ISSUE TITLE
Using the Block and Content wth ExpressJS and express-handlebars

### ISSUE THREAD

**Issue by custa1200** [assemble/handlebars-helpers#204]
Hi,
I am wanting to use the block and content helpers to inject items from my partials to slots in other partials or the base layout file that includes html,head, body etc. I require it straight after handlebars-helpers 
```
var exphbs  = require('express-handlebars');
var hbsHelpers = require('handlebars-helpers');
```

in my main.hbs template I have the following near the closing body tag
```
{{{block "test"}}}
```
and on a partial page I have 
```
{{#content "test" mode="append"}}
blah blah blah
{{/content}}
```

But when I run up the page it fails to load and I am presented with the following error
```
Error: Missing helper: "block"
   at Object.<anonymous> (/Users/custa/github/Portfolio/portfolioapp/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars/base.js:86:13)
   at Object.eval (eval at createFunctionContext (/Users/custa/github/Portfolio/portfolioapp/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:21:72)
   at ret (/Users/custa/github/Portfolio/portfolioapp/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
   at ret (/Users/custa/github/Portfolio/portfolioapp/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
   at ExpressHandlebars._renderTemplate (/Users/custa/github/Portfolio/portfolioapp/node_modules/express-handlebars/lib/express-handlebars.js:247:12)
   at ExpressHandlebars.<anonymous> (/Users/custa/github/Portfolio/portfolioapp/node_modules/express-handlebars/lib/express-handlebars.js:173:21)
   at wrappedPromise.linkTransaction (/Users/custa/github/Portfolio/portfolioapp/node_modules/newrelic/lib/instrumentation/core/globals.js:147:23)
   at wrappedPromise.wrapped [as __NR_wrapper] (/Users/custa/github/Portfolio/portfolioapp/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
   at wrappedHandler (/Users/custa/github/Portfolio/portfolioapp/node_modules/newrelic/lib/instrumentation/core/globals.js:175:26)
```

Not sure what I am doing wrong, do I have to somehow register the helpers? Anybody got any thoughts?

**Comment by ultra** [comment]
Hi,

After you create the express handlebars register the helpers.

For example:
```
var exphbs  = require('express-handlebars');
var hbsHelpers = require('handlebars-helpers');

var exhb = exphbs.create({ extname: 'hbs' });
hbsHelpers.register(exhb.handlebars, {});

app.engine('html', exhb.engine);

...
```

**Comment by custa1200** [comment]
When my code is changed to this (I have removed a heap of stuff that isn't to do with handlebars):
```
var express = require('express');
var path = require('path');
var exphbs  = require('express-handlebars');
var hbsHelpers = require('handlebars-helpers');
var changeCase = require('change-case');

var app = express();

var hbs = exphbs.create({
    extname: ".hbs",
    layoutsDir: path.join(__dirname, "views/layouts/"),
    partialsDir: path.join(__dirname, 'views/partials'),
    defaultLayout: 'main.hbs',
    helpers: {
        toKebabCase: function(value) {
                    if (value) {
                        return changeCase.paramCase(value);
                    } else {
                        return '';
                    }
        },
        contentBlock: function(name, options){
                    if(!this._contentBlocks) {
                        this._contentBlocks = {};
                    }
                    if(!this._contentBlocks[name]) {
                        this._contentBlocks[name] = [];
                    }
                    this._contentBlocks[name].push(options.fn(this));
        }
    }
});
hbsHelpers.register(exphbs.handlebars, {});

app.engine('hbs', hbs.engine);
app.set('view engine', 'hbs');
```
I get the following as an error
```
/Users/custa/github/Portfolio/portfolioapp/app.js:63
hbsHelpers.registerHelper(exphbs.handlebars, {});
           ^

TypeError: hbsHelpers.registerHelper is not a function
    at Object.<anonymous> (/Users/custa/github/Portfolio/portfolioapp/app.js:63:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/custa/github/Portfolio/portfolioapp/bin/www:7:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

**Comment by custa1200** [comment]
I should have used hbs instead of exphbs to have the following which works
```
hbsHelpers.register(hbs.handlebars, {});
```

**Comment by aplatov76** [comment]
nu i xyinya

**Comment by wahengchang** [comment]
same problem , how u guys fix it?

**Comment by kplatova97** [comment]
Hello, show me your code.
