### ISSUE TITLE
Error: Cannot find module 'grunt'

### ISSUE THREAD

**Issue by qcom** [assemble/handlebars-helpers#206]
Off a fresh install of `handlebars-helpers` I'm treated with the following:

```
Error: Cannot find module 'grunt'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/zach/node_modules/handlebars-helpers/lib/utils/utils.js:18:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/zach/node_modules/handlebars-helpers/lib/helper-lib.js:21:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/zach/node_modules/handlebars-helpers/index.js:1:80)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

node v4.2.2
handlebars-helpers v0.5.8

This first occurred with an existing `node_modules` directory but I got the same error after removing `node_modules`, running `npm cache clean`, and reinstalling.

**Comment by jonschlinkert** [comment]
duplicate

**Comment by qcom** [comment]
guess I could have looked harder to find what I assume to be the duplicate: #186 

nevertheless this hasn't been fixed since being opened in april? Is the solution to simply install grunt by hand? or modify `node_modules/handlebars-helpers/package.json`?

**Comment by jonschlinkert** [comment]
sorry, the focus is on the [dev branch](https://github.com/assemble/handlebars-helpers/tree/dev). If you or anyone else would like to help, I'm open to someone helping maintain the current branch so we can stay focused on getting the next release published. just let us know

**Comment by scarboroughventures** [comment]
if you do `npm install grunt --save` it will run.

**Comment by iamchristopher** [comment]
@jonschlinkert The documentation should be updated to reflect this focus. If your published codebase is not ready for production then a disclaimer should be posted.

For now I will have to find another lib to suit my needs, but I wish you luck with this project and hope I can count this lib among future project dependencies.
