### ISSUE TITLE
how to use handlebars-helpers in the express?(I use the express-handlebars)

### ISSUE THREAD

**Issue by strongwray** [assemble/handlebars-helpers#207]
I don't know how to use the handlebars-helpers, first i use require the module in my project,but has the problem,
module.js:340
    throw err;
    ^
Error: Cannot find module 'grunt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/***/node_connect_sxbCar/node_modules/handlebars-helpers/lib/utils/utils.js:18:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

this is dep the grunt? the doc has the helpers,but i don't know how to use ?Please help,thanks!!!

**Comment by keithamus** [comment]
@strongwray Grunt is a missing dependency from the this published module - that is to say that handlebars-helpers depends on it.

A quick fix is to simply run `npm install --save grunt` on your project, which should fix everything.

The [dev branch](https://github.com/assemble/handlebars-helpers/tree/dev) no longer requires Grunt. You could try out the dev branch by doing `npm i assemble/handlebars-helpers#dev`.

@jonschlinkert I think this one should be closed, just like #206 is. See also #157 #186 #187

**Comment by jonschlinkert** [comment]
Thanks @keithamus!
